"""empty message

Revision ID: 5aaee035a0be
Revises: 3f0cc2f43add
Create Date: 2022-08-10 14:32:56.100616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5aaee035a0be'
down_revision = '3f0cc2f43add'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venues', 'genres',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venues', 'genres',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
