"""empty message

Revision ID: 91acb7ecdfa2
Revises: 6f2e3d6d0ecb
Create Date: 2022-08-14 21:34:16.852652

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '91acb7ecdfa2'
down_revision = '6f2e3d6d0ecb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('start_time', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('shows', 'starting_time')
    op.add_column('venues', sa.Column('seeking_artist', sa.Boolean(), nullable=False))
    op.add_column('venues', sa.Column('seeking_description', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'seeking_description')
    op.drop_column('venues', 'seeking_artist')
    op.add_column('shows', sa.Column('starting_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('shows', 'start_time')
    # ### end Alembic commands ###
