"""empty message

Revision ID: 99259e9e6411
Revises: c0fbd029babf
Create Date: 2022-08-12 18:25:57.523812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99259e9e6411'
down_revision = 'c0fbd029babf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('Starting_Time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shows', 'Starting_Time')
    # ### end Alembic commands ###
