"""empty message

Revision ID: ce434ec58ab8
Revises: 91acb7ecdfa2
Create Date: 2022-08-20 01:18:29.591452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce434ec58ab8'
down_revision = '91acb7ecdfa2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('seeking_talent', sa.Boolean(), nullable=True))
    op.drop_column('venues', 'seeking_artist')
    op.execute('UPDATE venues  SET seeking_talent=True WHERE seeking_talent = NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('seeking_artist', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('venues', 'seeking_talent')
    # ### end Alembic commands ###
